apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata: 
      labels: 
        app: mongodb
    spec:   
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-username

        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-password
---
apiVersion: v1 
kind: Service
metadata:
  name: mongodb-service # um nome aleatório dado
spec:
  selector: # pra conectar ao pod pela label
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017 # porta do servico
      targetPort: 27017 # porta do container do deployment